apiVersion: v1
kind: ConfigMap
metadata:
  name: drkiq
  labels:
    app: drkiq
data:
  CACHE_URL: redis://redis:6379/0
  JOB_WORKER_URL: redis://redis:6379/0
  LISTEN_ON: 0.0.0.0:8000
  WORKER_PROCESSES: "1"
  


