apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ../../kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: drkiq
    app: drkiq
  name: drkiq
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: drkiq
        app: drkiq
    spec:
      containers:
      - env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: drkiq
              key: DATABASE_URL
        - name: SECRET_TOKEN
          value: asecuretokenwouldnormallygohere
        envFrom:
        - configMapRef:
            name: drkiq
        image: phawzy/drkiq:0.2
        name: drkiq
        ports:
        - containerPort: 8000
        resources: {}
      restartPolicy: Always
status: {}
